customCommands:
  - key: ''
    description: 'Open remote repository'
    context: 'status'
    command: 'open {{(index .SelectedRemote.Urls 0)}}'
  - key: 'e'
    description: 'Edit config file'
    context: 'status'
    command: 'nvim ~/Library/Application\ Support/lazygit/config.yml'
    subprocess: true
