customCommands:
  - key: ''
    description: 'Open remote repository'
    context: 'status'
    command: 'open {{(index .SelectedRemote.Urls 0)}}'
  - key: 'e'
    description: 'Edit config file'
    context: 'status'
    command: 'nvim ~/Library/Application\ Support/lazygit/config.yml'
    subprocess: true

  - key: 'C'
    command: 'cz commit'
    context: 'files'
    loadingText: 'opening commitizen commit tool'
    subprocess: true

  - key: 'X'
    description: 'custom commands'
    commandMenu:
    - key: ''
      context: 'commits'
      description: 'Ammend commit date attribute to the current date'
      command: 'git commit --allow-empty --only --no-edit --amend "--date=$(date -R)"'
      prompts:
      - type: 'confirm'
        title: 'Are you sure?'
        body: 'This operation performs an amend on a specific commit.'